#!/usr/bin/bash

set -eoux pipefail

echo "::group::Executing build-initramfs"
trap 'echo "::endgroup::"' EXIT
KERNEL_VERSION="6.15.9-201.fc42.x86_64"

# Szukamy wszystkich katalogów z modułami jądra
/usr/bin/dracut \
  --no-hostonly \
  --reproducible \
  --zstd \
  -v \
  --add ostree \
  --kver "$KERNEL_VERSION" \
  -f "/usr/lib/modules/$KERNEL_VERSION/initramfs.img"

