name: Build CritOS

on:
  schedule:
    - cron: "40 4 * * 1" # 4:40 UTC Monday
  push:
    branches:
      - testing
      - unstable
    paths-ignore:
      - "**.md"
      - "**.txt"
      - ".github/workflows/build_iso*.yml"
  pull_request:
    branches:
      - testing
      - unstable
    paths-ignore:
      - "**.md"
      - "**.txt"
      - ".github/workflows/build_iso*.yml"
  workflow_dispatch:

env:
  PULL_IMAGE_REGISTRY: ghcr.io/ublue-os
  PUSH_IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  push-ghcr:
    name: Make
    runs-on: ubuntu-24.04
    continue-on-error: false
    # job runs automatically only on testing/unstable, manual runs still allowed
    if: ${{ github.event_name == 'workflow_dispatch' || github.ref_name == 'testing' || github.ref_name == 'unstable' }}

    strategy:
      fail-fast: false
      matrix:
        base_image_flavor: [main]
        base_name: [critos]
        base_image_name: [kinoite]
        target_image_flavor: [main]
        target_nvidia_flavor: [nvidia, nvidia-open]
        fedora_version: [42]

    steps:
      - name: Mount btrfs for padman storage
        uses: ublue-os/container-storage-action@main
        with:
          target-dir: /var/lib/containers

      - name: Define env.CONTAINER_TARGET
        run: |
          if [[ "${{ matrix.base_name }}" == "critos-deck-nvidia" ]]; then
            echo "CONTAINER_TARGET=critos-nvidia" >> $GITHUB_ENV
          else
            echo "CONTAINER_TARGET=${{ matrix.base_name }}" >> $GITHUB_ENV
          fi

      - name: Define env.IMAGE_FLAVOR
        run: |
          if [[ "${{ matrix.base_name }}" =~ "nvidia" ]]; then
            if [[ "${{ matrix.target_image_flavor }}" == "main" ]]; then
              echo "IMAGE_FLAVOR=${{ matrix.target_nvidia_flavor }}" >> $GITHUB_ENV
            else
              echo "IMAGE_FLAVOR=${{ matrix.target_image_flavor }}-${{ matrix.target_nvidia_flavor }}" >> $GITHUB_ENV
            fi
          else
            echo "IMAGE_FLAVOR=${{ matrix.target_image_flavor }}" >> $GITHUB_ENV
          fi

      - name: Define env.IMAGE_NAME
        run: |
          DESKTOP=""
          if [[ "${{ matrix.base_image_name }}" == "silverblue" ]]; then
            DESKTOP="-gnome"
          fi

          if [[ "${{ matrix.base_name }}" == "critos-deck" ]]; then
            if [[ "${{ matrix.target_image_flavor }}" == "asus" ]]; then
              echo "IMAGE_NAME=critos-ally${DESKTOP}" >> $GITHUB_ENV
            else
              echo "IMAGE_NAME=critos-deck${DESKTOP}" >> $GITHUB_ENV
            fi
          elif [[ "${{ matrix.base_name }}" == "critos-deck-nvidia" ]]; then
            echo "IMAGE_NAME=critos-deck-nvidia${DESKTOP}" >> $GITHUB_ENV
          else
            if [[ "${{ env.IMAGE_FLAVOR }}" == "main" ]]; then
              echo "IMAGE_NAME=critos${DESKTOP}" >> $GITHUB_ENV
            else
              echo "IMAGE_NAME=critos${DESKTOP}-${{ env.IMAGE_FLAVOR }}" >> $GITHUB_ENV
            fi
          fi

      - name: Define env.NVIDIA_BASE
        run: |
          if [[ "${{ matrix.base_name }}" == "critos-deck-nvidia" ]]; then
            echo "NVIDIA_BASE=critos-deck" >> $GITHUB_ENV
          else
            echo "NVIDIA_BASE=critos" >> $GITHUB_ENV
          fi

      - name: Define env.SHA_HEAD_SHORT
        run: |
          echo "SHA_HEAD_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Authenticate to GHCR using GITHUB_TOKEN
        # required so skopeo can inspect ghcr.io images when private
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | skopeo login ghcr.io --username "${{ github.actor }}" --password-stdin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get source versions
        id: labels
        uses: Wandalen/wretry.action@v3.8.0
        with:
          attempt_limit: 3
          attempt_delay: 15000
          command: |
            set -eo pipefail
            skopeo inspect docker://${{ env.PULL_IMAGE_REGISTRY }}/${{ matrix.base_image_name }}-${{ matrix.base_image_flavor }}:${{ matrix.fedora_version }} > source.json
            ver=$(jq -r '.Labels["org.opencontainers.image.version"]' source.json)
            if [ -z "$ver" ] || [ "$ver" = "null" ]; then
              echo "inspected image version must not be empty or null" >&2
              exit 1
            fi
            echo "SOURCE_IMAGE_VERSION=$ver" >> $GITHUB_ENV

      - name: Generate Version
        id: generate-version
        shell: bash
        run: |
          UPSTREAM_TAG="${{ env.SOURCE_IMAGE_VERSION }}"
          UPSTREAM_TAG="${UPSTREAM_TAG%\.[0-9]}"
          FEDORA_VERSION="${{ matrix.fedora_version }}"
          SHA_SHORT="${GITHUB_SHA::7}"

          if [ -n "${{ github.event.pull_request.number }}" ]; then
            VERSION="pr-${FEDORA_VERSION}-${{ github.event.pull_request.number }}"
            PRETTY_VERSION="PR (${{ github.event.pull_request.number }}, ${UPSTREAM_TAG})"
          elif [[ ${{ github.ref_name }} == "unstable" ]]; then
            VERSION="unstable-${UPSTREAM_TAG}"
            PRETTY_VERSION="Unstable (F${UPSTREAM_TAG}, #${SHA_SHORT})"
          elif [[ ${{ github.ref_name }} == "testing" ]]; then
            VERSION="testing-${UPSTREAM_TAG}"
            PRETTY_VERSION="Testing (F${UPSTREAM_TAG}, #${SHA_SHORT})"
          else
            VERSION="${UPSTREAM_TAG}"
            PRETTY_VERSION="Stable (F${UPSTREAM_TAG})"
          fi

          echo "tag=${VERSION}" >> $GITHUB_OUTPUT
          echo "pretty=${PRETTY_VERSION}" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - name: Prepare build args file
        run: |
          cat > build_args.txt <<'EOF'
IMAGE_NAME=${{ env.IMAGE_NAME }}
IMAGE_FLAVOR=${{ env.IMAGE_FLAVOR }}
NVIDIA_FLAVOR=${{ matrix.target_nvidia_flavor }}
NVIDIA_BASE=${{ env.NVIDIA_BASE }}
IMAGE_VENDOR=${{ github.repository_owner }}
BASE_IMAGE_NAME=${{ matrix.base_image_name }}
BASE_IMAGE_FLAVOR=${{ matrix.base_image_flavor }}
FEDORA_VERSION=${{ matrix.fedora_version }}
IMAGE_BRANCH=${{ github.ref_name }}
SHA_HEAD_SHORT=${{ env.SHA_HEAD_SHORT }}
VERSION_TAG=${{ steps.generate-version.outputs.tag }}
VERSION_PRETTY=${{ steps.generate-version.outputs.pretty }}
EOF

      - name: Build Image
        id: build-image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo -E buildah build \
            --target "${{ env.CONTAINER_TARGET }}" \
            --build-arg-file build_args.txt \
            --secret "id=GITHUB_TOKEN,env=GITHUB_TOKEN" \
            --tag raw-img .

      - name: Lowercase Registry
        id: registry_case
        uses: ASzc/change-string-case-action@d0603cd0a7dd490be678164909f65c7737470a7f # v6
        with:
          string: ${{ env.PUSH_IMAGE_REGISTRY }}
