name: Build CritOS Linux Image UNSTABLE

on:
  schedule:
    - cron: "00 06 * * *"  # codziennie o 06:00 UTC
  push:
    paths-ignore:
      - "**.md"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  bluebuild:
    name: Build Custom UNSTABLE Image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build CritOS UNSTABLE Image
        uses: blue-build/github-action@v1.8
        with:
          recipe: recipe.yml
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}
          pr_event_number: ${{ github.event.number }}
          maximize_build_space: true

      - name: Create UNSTABLE GitHub Release (prerelease)
        if: github.event_name != 'pull_request'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=$(date +'%Y-%m-%d-%H%M')
          TAG="unstable-$DATE"
          MESSAGE=$(git log -1 --pretty=format:"%s")
          gh release create "$TAG" \
            --title "CritOS Unstable – $DATE" \
            --prerelease \
            --notes "$MESSAGE"
