name: Retag CritOS Latest to Stable

on:
  workflow_dispatch:  # ręczne uruchamianie z GitHub UI

jobs:
  retag:
    name: Retag and Push CritOS Stable
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull latest image
        run: |
          docker pull ghcr.io/${{ github.repository }}:latest

      - name: Retag as stable
        run: |
          docker tag ghcr.io/${{ github.repository }}:latest ghcr.io/${{ github.repository }}:stable

      - name: Push stable image
        run: |
          docker push ghcr.io/${{ github.repository }}:stable
